import { Link } from "react-router-dom";

import "./Hero.css";

const Hero = () => {
  return (
    <div class="box">
    <div class="infobox">
      <p class="infobox-boldtext">
        Imagine, discover, sharing and collect with extraordinary AI capability
      </p>
      <p class="infobox-slimtext">
      Make your imagination becomes visually stunning images generated by AI
      </p>
      <div class="infobox-btnwrapper">
        <button class="infobox-createbtn">
        <Link to="/create-post" >
          Create
        </Link>
        </button>
      </div>
    </div>
    <div class="display">
      <img class="display-nft" src="./photos/ai-bg.png" alt="hero" border="0"/>
      <div class="infowrapper">
        <div class="info-hero">
          <img class="info-img" src="https://images.unsplash.com/photo-1535207010348-71e47296838a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=385&q=80" alt="ava" border="0"/>
          <div>
            <p>Laura</p>
          </div>
  </div>
        <div class="info2">
          <p>Imagination</p>
        </div>
      </div>
    </div>
  </div>
  )
}

export default Hero;